#!/bin/bash

# Definitions
DIR_GIT="$HOME/git"
PKG_BASE="sddm xterm polkit-gnome picom arandr sxhkd wmctrl alacritty \
xorg-xset xorg-mkfontscale xorg-xev xscreensaver xdg-user-dirs \
pcmanfm pavucontrol pasystray galculator geeqie vlc screengrab rofi gpick parcellite mousepad \
gparted udiskie gvfs gvfs-mtp gvfs-nfs gvfs-smb filezilla gufw qbittorrent \
openssh network-manager-applet firefox lxappearance kvantum dconf-editor gnome-disk-utility \
ttf-dejavu ttf-ibm-plex noto-fonts ttf-roboto ttf-roboto-mono"
PKG_BASE_AUR="windowmaker windowmaker-extra xdgmenumaker sddm-conf picom-conf downgrade etcher-bin"
PKG_APP_GFX="gimp gimp-plugin-gmic inkscape"
PKG_APP_MEDIA="audacity blender handbrake kdenlive obs-studio soundconverter"

# Functions
# Yes/No function
ask_yes_no() {
    while true; do
        read -p "$1 (y/n): " answer
        case $answer in
            [Yy]* ) return 0;;  # Yes
            [Nn]* ) return 1;;  # No
            * ) echo "Please answer yes or no.";;
        esac
    done
}

echo "--------------------------------"
echo "Window Maker Desktop Environment"
echo "--------------------------------"

# start install
if ask_yes_no "Begin installation?"; then
    sudo pacman -S --needed git base-devel --noconfirm
else
    echo "Installation cancelled."
    exit
fi
# install yay
echo "Installing yay..."
cd /tmp
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd
# install base packages
echo "Installing base packages..."
sudo pacman -S  $PKG_BASE --noconfirm
yay -S $PKG_BASE_AUR --noconfirm
echo " "
# install graphics applications
if ask_yes_no "Install graphics applications?"; then
sudo pacman -S $PKG_GFX --noconfirm
else
    echo "Skipped graphics applications."
fi
echo " "
# install multimedia applications
if ask_yes_no "Install audio/video editing applications?"; then
sudo pacman -S $PKG_MEDIA --noconfirm
else
    echo "Skipped audio/video applications."
fi
echo " "

# link WPrefs
sudo ln -s /usr/lib/GNUstep/Applications/WPrefs.app/WPrefs /usr/bin/WPrefs
