#!/bin/bash
# WMDE Installer 0.2
# 14/01/26

# Locations
DIR_SCRIPT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIR_WMDE="$HOME/.wmde"
DIR_BACKUP="$HOME/.wmde/preinstall"

# Definitions
TITLE="Window Maker Desktop Environment"

# Functions
install_from_file() {
    local file=$1
    if [[ -f "$file" ]]; then
        grep -vE '^\s*#|^\s*$' "$file" | xargs -r yay -S --needed --noconfirm
    else
        echo "Warning: $file not found."
    fi
}

CHECK_WHIPTAIL() {
	if command -v whiptail >/dev/null; then
		echo "Starting WMDE installer"
	else
		echo "Whiptail not found! Installing now..." && sleep 1
		sudo pacman -S libnewt --noconfirm
	fi
}

INST_THEMES() {
	cd $DIR_SCRIPT/files/themes
	mkdir -p "$HOME/.themes"
	for zipfile in gtk_*.zip; do
	    if [[ -f "$zipfile" ]]; then
	        echo "Extracting $zipfile..."
	        unzip -o "$zipfile" -d "$HOME/.themes"
	    else
	        echo "No files starting with 'gtk_' found."
	    fi
	done	
}

INST_DOCKAPPS() {
	# wmsystemtray font fix
	cd /usr/share/fonts/misc
	sudo mkfontscale
	sudo mkfontdir
	sudo xset fp rehash
	cd $DIR_SOURCE
}

INST_CONFIG() {
	cp -a $DIR_SCRIPT/files/config/. $HOME/.config
	cp -a $DIR_SCRIPT/files/wmde/. $HOME/.wmde
}

CONFIG_GENERAL() {
	grep -q "Xft.dpi:" ~/.Xresources || echo "Xft.dpi: 96" >> $HOME/.Xresources
}

# Whiptail pages
PAGE_INSTALL() {
	PKG_BASE="$DIR_SCRIPT/includes/pkg_base"
	PKG_BASE_AUR="$DIR_SCRIPT/includes/pkg_base_aur"
	
	if whiptail --title "$TITLE" --yesno \
		"WMDE is a preconfigured Window Maker desktop environment for Arch Linux based systems.\n\n\
For more information visit wmde.goreshit.co.uk\n\n\
Update system and begin installation?" 12 60; then
			echo "Updating system..." && sleep 1
			sudo pacman -Syu --needed git base-devel --noconfirm
		else
			echo "Installation cancelled."
			exit 0
		fi

		if ! command -v yay >/dev/null; then
			echo "yay not found. Installing now..." && sleep 1
			cd /tmp || exit
			git clone https://aur.archlinux.org/yay.git
			cd yay && makepkg -si --noconfirm
			yay -Syu
			cd "$DIR_SCRIPT" || exit
		fi
		
		echo "Installing base packages..." && sleep 1
		cat "$PKG_BASE" "$PKG_BASE_AUR" | grep -vE '^\s*#|^\s*$' | xargs -r yay -S --needed --noconfirm
}

PAGE_BACKUP() {
	if whiptail --title "$TITLE" --yesno "Backup configuration files?\n
	Creates a backup of any files WMDE may replace.\n
	(can be found in the .wmde/preinstall folder of your home directory)" 10 60; then
	    echo "Backing up config files..." && sleep 1
	    mkdir -p $DIR_BACKUP/.config || { echo "Error: Could not create $DIR_BACKUP"; return 1; }
	    for file in .Xresources .xprofile .xinitrc; do
	    	[ -f "$HOME/$file" ] && cp -a "$HOME/$file" "$DIR_BACKUP/"
	    done
	    for folder in "gtk-3.0" "gtk-4.0"; do
	    	[ -d "$HOME/.config/$folder" ] && cp -a "$HOME/.config/$folder" "$DIR_BACKUP/.config"
	    done
	else
	    echo "Skipping config backup." && sleep 1
	fi
}

PAGE_COMPUTER() {
	if whiptail --title "$TITLE" --yes-button "Desktop" --no-button "Laptop" --yesno "Select computer type:" 8 60; then
	    echo "Configuring system for a DESKTOP computer..." && sleep 1
	else
	    echo "Configuring system for a LAPTOP computer..." && sleep 1
	fi
}

# Running order
PAGE_INSTALL
PAGE_BACKUP
INST_THEMES
INST_DOCKAPPS
INST_CONFIG
CONFIG_GENERAL
PAGE_COMPUTER
